Main-Settings:
  Teleport-delay:
    enabled: true
    #Called in ticks. Max 600 ticks = 30 seconds
    time-to-teleport: 60

  Commands:
    Request:
      auto-cancel: true
      #Called in ticks. Max 6000 ticks = 5 minutes
      time-to-cancel: 1200

Gui:
  #It's shows gui with player's homes. Clicked item will teleport you to selected home.
  show: true
  #You need to specify the amount of rows.
  size: 1
  Materials:
    #Plugin will automatically select a random material to specified home.
    random: false
    #Custom - One material type to all homes in gui
    custom:
      material: FEATHER
      enabled: true

Limits:
  #If true, player need permission. - Example: homes.limit.2
  enabled: true

  #Needs permission - homes.limit.bypass
  bypass-for-admins: true

  #This option is responsible for the number of repetitions of checking the player's permissions. !! Enter carefully !!
  #It's best to leave the default value
  max: 100

#Soon
Hooks:
  WorldGuard:
    enabled: false

  PlotSquared:
    enabled: false

  BentoBox:
    enabled: false

#Don't change this value!
Config-Version: 2.0