Main-Settings:
  Teleport-delay:
    enabled: true
    #Called in ticks. Max 600 ticks = 30 seconds
    time-to-teleport: 60
    #Requires permission: homes.delay.bypass
    bypass-for-admins: true

  Commands:
    Request:
      auto-cancel: true
      #Called in ticks. Max 6000 ticks = 5 minutes
      time-to-cancel: 1200

Gui:
  #It's shows gui with player's homes. Clicked item will teleport you to selected home.
  show: true
  #You need to specify the amount of rows.
  size: 1
  title: 'You can use Legacy or MiniMessage colors input type.'
  item-name-color: '&r&c&l<name>'
  Materials:
    #Plugin will automatically select a random material to specified home.
    random: false
    #Custom - One material type to all homes in gui
    custom:
      material: 'FEATHER'

Limits:
  #If true, player need permission. - Example: homes.limit.2
  enabled: true

  #Needs permission - homes.limit.bypass
  bypass-for-admins: true

  #This option is responsible for the number of repetitions of checking the player's permissions. !! Enter carefully !!
  #It's best to leave the default value
  max: 100

#Soon
Hooks:
  WorldGuard:
    enabled: false
    bypass-for-admins: true
    #PROTECTIONSTONES = Choosing this you can block uninvited guests from setting homes on players plots and checking ignored-regions
    #DEFAULT = It's checking only blacklisted-regions and whitelisted-regions
    secure-type: DEFAULT
    whitelisted-regions:
      - 'example'
    blacklisted-regions:
      - 'example'
    #Only in PROTECTIONSTONES secure type
    ignored-regions:
      - 'example'

  PlotSquared:
    enabled: false

  BentoBox:
    enabled: false

#Don't change this value!
Config-Version: 2.0